version: '3.8'

services:
  backend:
    image: ghcr.io/nahankar/shatika-backend:latest
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://admindb:admindb@shatika0.upf2h.mongodb.net/shatika?retryWrites=true&w=majority&appName=shatika0
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - CLOUDINARY_CLOUD_NAME=dfashwxf0
      - CLOUDINARY_API_KEY=625616318298377
      - CLOUDINARY_API_SECRET=bcVA_ZCrscBO6crf9FJF4UKVORQ
    volumes:
      - ./temp:/app/temp
    restart: always

  frontend:
    image: ghcr.io/nahankar/shatika-frontend:latest
    environment:
      - VITE_API_URL=http://144.24.135.139:5001
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always 